### ISSUE TITLE
Active label

### ISSUE THREAD

**Issue by gusilveiramp** [timomeh/react-native-material-bottom-navigation#49] opened 2017-10-04 18:42 UTC
Hi, 

How to use like that? https://github.com/timomeh/react-native-material-bottom-navigation/blob/master/.github/color-4-tab.gif

**Comment by timomeh** [comment] 2017-10-04 19:46
There is code for this exact example [directly in the second chapter "But how? (Usage)" of the README](https://github.com/timomeh/react-native-material-bottom-navigation#but-how). Also, there's a directory called [`/example`](https://github.com/timomeh/react-native-material-bottom-navigation/tree/master/example) with three examples for standalone usage or usage together with [react-navigation](https://github.com/react-community/react-navigation). All examples will reproduce the exact gif you referenced. The [react-navigation example](https://github.com/timomeh/react-native-material-bottom-navigation/blob/ad715afd6369126116cd3cf9f34014e4ec30111e/example/ReactNavigationBottomNavigation.js) has just three tabs, but adding a fourth tab shouldn't be that hard.

I'm going to close this issue since the README and the examples provide all the necessary informations to get you started. If you think there are some missing informations, please explain what is missing and/or should be improved.

**Closed as completed by timomeh** 2017-10-04 19:46 UTC
