### ISSUE TITLE
 Is there any possibility to remove label?

### ISSUE THREAD

**Issue by omriattiya** [timomeh/react-native-material-bottom-navigation#80] opened 2018-03-20 12:32 UTC
Hi, i'm currently using react-native-material-bottom-navigation.
Can I somehow remove the label or the animation when the tab pressed?
I want to use only icon and center it in the bottom bar.

Thanks :D

**Comment by timomeh** [comment] 2018-03-20 12:41
Duplicate of #31, #77, #22, #19, and #15. I'm currently working on a complete rewrite which will include this feature. See #76 for progress

Closing this since #31 is still open.

**Closed as completed by timomeh** 2018-03-20 12:41 UTC
Labels: 🖇 duplicate
