### ISSUE TITLE
having no label?

### ISSUE THREAD

**Issue by hwnprsd** [timomeh/react-native-material-bottom-navigation#77] opened 2018-03-06 14:06 UTC
- () Bug Report
- (x) Question / Problem
- (x) Discussion / Feature Request

The react-navigations's `showLabel` config option is ruled out by this library. So, An option to not have labels so that the icons are centered correctly is really important.

I really couldn't find a solution other than making the label color, the color of the bg. If im wrong, please do point me at the right config

**Comment by timomeh** [comment] 2018-03-06 14:18
Duplicate of #31, #22, #19 

I'm currently in progress of rewriting the BottomNavigation, which will include a Tab without a label. You can check (or subscribe) #76 to check the progress of this feature.

**Closed as completed by timomeh** 2018-03-06 14:18 UTC
Labels: 🖇 duplicate
