### ISSUE TITLE
the example totally not works for me

### ISSUE THREAD

**Issue by flyinghawker** [timomeh/react-native-material-bottom-navigation#90] opened 2018-05-29 03:44 UTC
I tried the example but totally not work. The example code structure looks outdated.

**Comment by timomeh** [comment] 2018-05-29 06:58
First of all, you didn't fill out the Issue Template. Your issue is lacking important informations like version numbers and reproductible examples.

The example app, as well as the Readme and the Docs _are_ up-to-date.  
You can download examples/Playground and run it locally thanks to Expo. This is the same App with which I test and experiment locally, so it's up-to-date.

Also, v1.0.0 was just released 2 weeks ago, so nothing should be outdated. ☺️ That being said, please make sure you're actually using v1.0.0.

If you have further questions, please specify what exactly doesn't work (e.g. are there any errors?) and share code examples.

I'm going to close this issue since it's very vague, but you can still comment.

**Closed as completed by timomeh** 2018-05-29 06:58 UTC
Labels: 🚫 invalid, ⚠️ missing issue template
